---
- name: Cek koneksi SSH ke host
  hosts: all
  gather_facts: no

  tasks:
    - name: Jalankan perintah 'whoami' pakai raw
      raw: whoami
      register: hasil

    - name: Tampilkan hasil
      debug:
        msg: "Login sebagai: {{ hasil.stdout }}"
