---
- name: Ambil informasi sistem operasi
  hosts: all
  gather_facts: yes

  tasks:
    - name: Tampilkan informasi OS
      debug:
        msg: >
          Sistem operasi: {{ ansible_distribution }} {{ ansible_distribution_version }}
          - Kernel: {{ ansible_kernel }}
          - Arsitektur: {{ ansible_architect
