---
- name: Cek OS dan service lalu kirim ke webhook
  hosts: all
  gather_facts: no

  tasks:
    - name: Cek informasi OS
      raw: uname -a
      register: os_info

    - name: Cek daftar service
      raw: ps -eo pid,comm
      register: service_info
